# Generated by Django 4.1.4 on 2023-01-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.city'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.city'),
        ),
    ]
