# Generated by Django 4.1.4 on 2023-01-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.city'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.company'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.occupation'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='vacancy',
            field=models.ManyToManyField(related_name='specializations', to='database.vacancy'),
        ),
        migrations.AddField(
            model_name='skill',
            name='specialization',
            field=models.ManyToManyField(related_name='skills', to='database.specialization'),
        ),
        migrations.AddField(
            model_name='response',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.client'),
        ),
        migrations.AddField(
            model_name='response',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.vacancy'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.client'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.vacancy'),
        ),
    ]
