# Generated by Django 4.1.4 on 2023-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_vacancy_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="response_text",
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
    ]
