# Generated by Django 4.1.4 on 2023-05-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_response_response_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="specialization",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="occupation",
            field=models.ManyToManyField(blank=True, to="database.occupation"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="specialization",
            field=models.ManyToManyField(blank=True, to="database.specialization"),
        ),
    ]
