# Generated by Django 4.1.4 on 2023-05-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_remove_vacancy_occupation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialization",
            name="skills",
        ),
        migrations.AddField(
            model_name="specialization",
            name="skills",
            field=models.ManyToManyField(blank=True, to="database.skill"),
        ),
    ]
