# Generated by Django 4.1.4 on 2023-05-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_remove_specialization_skills_specialization_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialization",
            name="skills",
        ),
        migrations.AddField(
            model_name="skill",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialization",
                to="database.specialization",
            ),
        ),
    ]
